source "http://rubygems.org"

gem "sinatra", "1.2.6"
gem "sinatra-redirect-with-flash", "0.1.2"
gem "sqlite3", "1.3.3"
gem "dm-aggregates", "1.1.0"
gem "dm-constraints", "1.1.0"
gem "dm-core", "1.1.0"
gem "dm-do-adapter", "1.1.0"
gem "dm-migrations", "1.1.0"
gem "dm-sqlite-adapter", "1.1.0"
gem "dm-timestamps", "1.1.0"
gem "dm-transactions", "1.1.0"
gem "dm-validations", "1.1.0"
gem "rack-flash", "0.1.1"