source "http://rubygems.org"

gem "sinatra"
gem "sinatra-redirect-with-flash"
gem "sqlite3"
gem "dm-aggregates"
gem "dm-constraints"
gem "dm-core"
gem "dm-do-adapter"
gem "dm-migrations"
gem "dm-sqlite-adapter"
gem "dm-timestamps"
gem "dm-transactions"
gem "dm-validations"
gem "rack-flash"
gem "data_mapper"